name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Setup .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        # Comment out or adjust database configuration for initial deployment
        sed -i '/^DB_/ s/^/#/' .env

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a travelsite
        git push heroku main
